# Generated by Django 5.1.2 on 2025-07-07 21:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mmr', models.IntegerField(default=2000)),
            ],
            options={
                'ordering': ['-mmr', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('1v1', '1 vs 1'), ('2v1', '2 vs 1'), ('2v2', '2 vs 2')], max_length=3)),
                ('match_format', models.CharField(choices=[('BO1', 'Best of 1'), ('BO3', 'Best of 3'), ('BO5', 'Best of 5')], max_length=3)),
                ('is_ranked', models.BooleanField(default=True)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('team1_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('team2_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('team1_player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches_p1', to='pool.player')),
                ('team1_player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches_p2', to='pool.player')),
                ('team2_player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches_p1', to='pool.player')),
                ('team2_player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches_p2', to='pool.player')),
            ],
            options={
                'ordering': ['-date_played'],
            },
        ),
    ]
