# Generated by Django 5.1.2 on 2025-07-07 21:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date_played'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-mmr', 'name'], 'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterField(
            model_name='match',
            name='is_ranked',
            field=models.BooleanField(default=True, verbose_name='Ranked Match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_format',
            field=models.CharField(choices=[('BO1', 'Best of 1 Quickshot'), ('BO3', 'Best of 3 Challenge'), ('BO5', 'Best of 5 Epic')], max_length=3),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('1v1', '1 vs 1 Showdown'), ('2v1', '2 vs 1 Clash'), ('2v2', '2 vs 2 Battle')], max_length=3),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1_player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches_p1', to='pool.player', verbose_name='Team 1 Player 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1_player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches_p2', to='pool.player', verbose_name='Team 1 Player 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Team 1 Score'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches_p1', to='pool.player', verbose_name='Team 2 Player 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches_p2', to='pool.player', verbose_name='Team 2 Player 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Team 2 Score'),
        ),
    ]
