# Generated by Django 5.1.2 on 2025-07-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_alter_match_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
